### ISSUE TITLE
Reklamlar birkez daha açılmıyor

### ISSUE THREAD

**Issue by 1emirozdemir** [judix-e/Admob-Banner-interstitial-for-android#1]
Merhaba banner reklamda sıkıntı yokta geçiş reklamlarında reklam uygulama açılırken birkez açılıyor daha sonra hiç açılmıyor. OnBack metedu ile ayarlayabiliriz diye not düşmüssün fakat böyle bir metod yok admob classında

**Comment by judix** [comment]
> Merhaba banner reklamda sıkıntı yokta geçiş reklamlarında reklam uygulama açılırken birkez açılıyor daha sonra hiç açılmıyor. OnBack metedu ile ayarlayabiliriz diye not düşmüssün fakat böyle bir metod yok admob classında

Merhaba henüz yanıt verdiğim için üzgünüm Admob reklamları onBack metodunda kullanılması doğru bir davranış değildir bu nedenle yazıyı düzelteceğim.
Reklamlar istenilen sınıflarda bir kez çağrılıyor yada bir işlevde çağrılıyor arka arkaya reklam çağırmak da kullanıcıyı sıkar.

**Comment by judix** [comment]
> Merhaba banner reklamda sıkıntı yokta geçiş reklamlarında reklam uygulama açılırken birkez açılıyor daha sonra hiç açılmıyor. OnBack metedu ile ayarlayabiliriz diye not düşmüssün fakat böyle bir metod yok admob classında

Merhaba henüz yanıt verdiğim için üzgünüm Admob reklamları onBack metodunda kullanılması doğru bir davranış değildir bu nedenle yazıyı düzelteceğim.
Reklamlar istenilen sınıflarda bir kez çağrılıyor yada bir işlevde çağrılıyor arka arkaya reklam çağırmak da kullanıcıyı sıkar.
